window.GAMES = [
    {
        "id": "2048",
        "slug": "2048-game",
        "title": "2048",
        "category": "sports",
        "creator": "A23 Games",
        "path": "games/2048/index.html",
        "thumbnail": "assets/thumbs/2048.png",
        "description": "Play 2048 online for free!",
        "longDescription": "Experience the thrill of 2048. Complete challenges, achieve high scores, and enjoy this engaging sports game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": true
    },
    {
        "id": "2048-advanced",
        "slug": "2048-advanced-game",
        "title": "2048 Advanced",
        "category": "action",
        "creator": "A23 Games",
        "path": "games/2048-advanced/index.html",
        "thumbnail": "games/2048-advanced/assets/icons/icon.svg",
        "description": "Play 2048 Advanced online for free!",
        "longDescription": "Experience the thrill of 2048 Advanced. Complete challenges, achieve high scores, and enjoy this engaging action game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "airbattlemission",
        "slug": "airbattlemission-game",
        "title": "Airbattlemission",
        "category": "strategy",
        "creator": "A23 Games",
        "path": "games/airbattlemission/index.html",
        "thumbnail": "games/airbattlemission/icon-256.png",
        "description": "Play Airbattlemission online for free!",
        "longDescription": "Experience the thrill of Airbattlemission. Complete challenges, achieve high scores, and enjoy this engaging strategy game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "airport-security-check",
        "slug": "airport-security-check-game",
        "title": "Airport Security Check",
        "category": "sports",
        "creator": "A23 Games",
        "path": "games/airport-security-check/index.html",
        "thumbnail": "games/airport-security-check/assets/images/game_icon.png",
        "description": "Play Airport Security Check online for free!",
        "longDescription": "Experience the thrill of Airport Security Check. Complete challenges, achieve high scores, and enjoy this engaging sports game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "airportmadness-node",
        "slug": "airportmadness-node-game",
        "title": "AirportMadness Node",
        "category": "racing",
        "creator": "A23 Games",
        "path": "games/AirportMadness-node/Deploy/index.html",
        "thumbnail": "games/AirportMadness-node/Deploy/img/airport1.png",
        "description": "Play AirportMadness Node online for free!",
        "longDescription": "Experience the thrill of AirportMadness Node. Complete challenges, achieve high scores, and enjoy this engaging racing game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "alien-farming-colony",
        "slug": "alien-farming-colony-game",
        "title": "Alien Farming Colony",
        "category": "strategy",
        "creator": "A23 Games",
        "path": "games/alien-farming-colony/index.html",
        "thumbnail": "games/alien-farming-colony/assets/icons/icon.svg",
        "description": "Play Alien Farming Colony online for free!",
        "longDescription": "Experience the thrill of Alien Farming Colony. Complete challenges, achieve high scores, and enjoy this engaging strategy game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "archer-defense",
        "slug": "archer-defense-game",
        "title": "Archer Defense",
        "category": "strategy",
        "creator": "A23 Games",
        "path": "games/archer-defense/index.html",
        "thumbnail": "games/archer-defense/assets/thumb.png",
        "description": "Play Archer Defense online for free!",
        "longDescription": "Experience the thrill of Archer Defense. Complete challenges, achieve high scores, and enjoy this engaging strategy game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "balloon_blitz",
        "slug": "balloon-blitz-game",
        "title": "Balloon Blitz",
        "category": "action",
        "creator": "A23 Games",
        "path": "games/balloon blitz/index.html",
        "thumbnail": "games/balloon blitz/icons/loading-logo.png",
        "description": "Play Balloon Blitz online for free!",
        "longDescription": "Experience the thrill of Balloon Blitz. Complete challenges, achieve high scores, and enjoy this engaging action game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "basketball-trick-shots",
        "slug": "basketball-trick-shots-game",
        "title": "Basketball Trick Shots",
        "category": "puzzle",
        "creator": "A23 Games",
        "path": "games/basketball-trick-shots/index.html",
        "thumbnail": "games/basketball-trick-shots/assets/images/icon.png",
        "description": "Play Basketball Trick Shots online for free!",
        "longDescription": "Experience the thrill of Basketball Trick Shots. Complete challenges, achieve high scores, and enjoy this engaging puzzle game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "battle-royale-mini-arena",
        "slug": "battle-royale-mini-arena-game",
        "title": "Battle Royale Mini Arena",
        "category": "racing",
        "creator": "A23 Games",
        "path": "games/battle-royale-mini-arena/index.html",
        "thumbnail": "games/battle-royale-mini-arena/assets/icons/icon.png",
        "description": "Play Battle Royale Mini Arena online for free!",
        "longDescription": "Experience the thrill of Battle Royale Mini Arena. Complete challenges, achieve high scores, and enjoy this engaging racing game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "bike-stunt-master",
        "slug": "bike-stunt-master-game",
        "title": "Bike Stunt Master",
        "category": "sports",
        "creator": "A23 Games",
        "path": "games/bike-stunt-master/index.html",
        "thumbnail": "games/bike-stunt-master/assets/images/icon.svg",
        "description": "Play Bike Stunt Master online for free!",
        "longDescription": "Experience the thrill of Bike Stunt Master. Complete challenges, achieve high scores, and enjoy this engaging sports game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "bomb-defuse-puzzle",
        "slug": "bomb-defuse-puzzle-game",
        "title": "Bomb Defuse Puzzle",
        "category": "racing",
        "creator": "A23 Games",
        "path": "games/bomb-defuse-puzzle/index.html",
        "thumbnail": "games/bomb-defuse-puzzle/assets/thumb.png",
        "description": "Play Bomb Defuse Puzzle online for free!",
        "longDescription": "Experience the thrill of Bomb Defuse Puzzle. Complete challenges, achieve high scores, and enjoy this engaging racing game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": true
    },
    {
        "id": "brick-breaker",
        "slug": "brick-breaker-game",
        "title": "Brick Breaker",
        "category": "sports",
        "creator": "A23 Games",
        "path": "games/brick-breaker/index.html",
        "thumbnail": "games/brick-breaker/assets/icon.png",
        "description": "Play Brick Breaker online for free!",
        "longDescription": "Experience the thrill of Brick Breaker. Complete challenges, achieve high scores, and enjoy this engaging sports game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "bridge-construction-simulator",
        "slug": "bridge-construction-simulator-game",
        "title": "Bridge Construction Simulator",
        "category": "arcade",
        "creator": "A23 Games",
        "path": "games/bridge-construction-simulator/index.html",
        "thumbnail": "games/bridge-construction-simulator/assets/icons/icon.png",
        "description": "Play Bridge Construction Simulator online for free!",
        "longDescription": "Experience the thrill of Bridge Construction Simulator. Complete challenges, achieve high scores, and enjoy this engaging arcade game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "bridge-crossing-challenge",
        "slug": "bridge-crossing-challenge-game",
        "title": "Bridge Crossing Challenge",
        "category": "puzzle",
        "creator": "A23 Games",
        "path": "games/bridge-crossing-challenge/index.html",
        "thumbnail": "games/bridge-crossing-challenge/assets/thumb.png",
        "description": "Play Bridge Crossing Challenge online for free!",
        "longDescription": "Experience the thrill of Bridge Crossing Challenge. Complete challenges, achieve high scores, and enjoy this engaging puzzle game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "bubble-pop",
        "slug": "bubble-pop-game",
        "title": "Bubble Pop",
        "category": "puzzle",
        "creator": "A23 Games",
        "path": "games/bubble-pop/index.html",
        "thumbnail": "games/bubble-pop/icon.png",
        "description": "Play Bubble Pop online for free!",
        "longDescription": "Experience the thrill of Bubble Pop. Complete challenges, achieve high scores, and enjoy this engaging puzzle game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "cannon-target-strike",
        "slug": "cannon-target-strike-game",
        "title": "Cannon Target Strike",
        "category": "racing",
        "creator": "A23 Games",
        "path": "games/cannon-target-strike/index.html",
        "thumbnail": "games/cannon-target-strike/assets/thumb.png",
        "description": "Play Cannon Target Strike online for free!",
        "longDescription": "Experience the thrill of Cannon Target Strike. Complete challenges, achieve high scores, and enjoy this engaging racing game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "canvas_tower_defense",
        "slug": "canvas_tower_defense-game",
        "title": "Canvas Tower Defense",
        "category": "action",
        "creator": "A23 Games",
        "path": "games/canvas_tower_defense/index.html",
        "thumbnail": "assets/thumbs/canvas_tower_defense.png",
        "description": "Play Canvas Tower Defense online for free!",
        "longDescription": "Experience the thrill of Canvas Tower Defense. Complete challenges, achieve high scores, and enjoy this engaging action game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "car-race",
        "slug": "car-race-game",
        "title": "Car Race",
        "category": "sports",
        "creator": "A23 Games",
        "path": "games/car-race/index.html",
        "thumbnail": "games/car-race/icons/loading-logo.png",
        "description": "Play Car Race online for free!",
        "longDescription": "Experience the thrill of Car Race. Complete challenges, achieve high scores, and enjoy this engaging sports game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "car-racing-game",
        "slug": "car-racing-game-game",
        "title": "Car Racing Game",
        "category": "strategy",
        "creator": "A23 Games",
        "path": "games/car-racing-game/index.html",
        "thumbnail": "games/car-racing-game/assets/images/player_car.png",
        "description": "Play Car Racing Game online for free!",
        "longDescription": "Experience the thrill of Car Racing Game. Complete challenges, achieve high scores, and enjoy this engaging strategy game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "chess-game",
        "slug": "chess-game-game",
        "title": "Chess Game",
        "category": "puzzle",
        "creator": "A23 Games",
        "path": "games/chess-game/index.html",
        "thumbnail": "games/chess-game/assets/images/icon.png",
        "description": "Play Chess Game online for free!",
        "longDescription": "Experience the thrill of Chess Game. Complete challenges, achieve high scores, and enjoy this engaging puzzle game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "city-builder-tycoon",
        "slug": "city-builder-tycoon-game",
        "title": "City Builder Tycoon",
        "category": "action",
        "creator": "A23 Games",
        "path": "games/city-builder-tycoon/index.html",
        "thumbnail": "games/city-builder-tycoon/assets/icon.svg",
        "description": "Play City Builder Tycoon online for free!",
        "longDescription": "Experience the thrill of City Builder Tycoon. Complete challenges, achieve high scores, and enjoy this engaging action game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "city-devour-hole-3d",
        "slug": "city-devour-hole-3d-game",
        "title": "City Devour Hole 3d",
        "category": "racing",
        "creator": "A23 Games",
        "path": "games/city-devour-hole-3d/index.html",
        "thumbnail": "games/city-devour-hole-3d/assets/icons/icon.svg",
        "description": "Play City Devour Hole 3d online for free!",
        "longDescription": "Experience the thrill of City Devour Hole 3d. Complete challenges, achieve high scores, and enjoy this engaging racing game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": true
    },
    {
        "id": "color-switch-advanced",
        "slug": "color-switch-advanced-game",
        "title": "Color Switch Advanced",
        "category": "strategy",
        "creator": "A23 Games",
        "path": "games/color-switch-advanced/index.html",
        "thumbnail": "games/color-switch-advanced/assets/thumb.png",
        "description": "Play Color Switch Advanced online for free!",
        "longDescription": "Experience the thrill of Color Switch Advanced. Complete challenges, achieve high scores, and enjoy this engaging strategy game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "cooking-battle-arena",
        "slug": "cooking-battle-arena-game",
        "title": "Cooking Battle Arena",
        "category": "arcade",
        "creator": "A23 Games",
        "path": "games/cooking-battle-arena/index.html",
        "thumbnail": "games/cooking-battle-arena/assets/icons/icon.png",
        "description": "Play Cooking Battle Arena online for free!",
        "longDescription": "Experience the thrill of Cooking Battle Arena. Complete challenges, achieve high scores, and enjoy this engaging arcade game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "cube-adventure-platformer",
        "slug": "cube-adventure-platformer-game",
        "title": "Cube Adventure Platformer",
        "category": "strategy",
        "creator": "A23 Games",
        "path": "games/cube-adventure-platformer/index.html",
        "thumbnail": "games/cube-adventure-platformer/assets/thumb.png",
        "description": "Play Cube Adventure Platformer online for free!",
        "longDescription": "Experience the thrill of Cube Adventure Platformer. Complete challenges, achieve high scores, and enjoy this engaging strategy game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "delivery-bike-rush",
        "slug": "delivery-bike-rush-game",
        "title": "Delivery Bike Rush",
        "category": "racing",
        "creator": "A23 Games",
        "path": "games/delivery-bike-rush/index.html",
        "thumbnail": "games/delivery-bike-rush/assets/thumb.png",
        "description": "Play Delivery Bike Rush online for free!",
        "longDescription": "Experience the thrill of Delivery Bike Rush. Complete challenges, achieve high scores, and enjoy this engaging racing game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "delivery-rush-simulator",
        "slug": "delivery-rush-simulator-game",
        "title": "Delivery Rush Simulator",
        "category": "racing",
        "creator": "A23 Games",
        "path": "games/delivery-rush-simulator/index.html",
        "thumbnail": "assets/thumbs/delivery-rush-simulator.png",
        "description": "Play Delivery Rush Simulator online for free!",
        "longDescription": "Experience the thrill of Delivery Rush Simulator. Complete challenges, achieve high scores, and enjoy this engaging racing game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "digital-pet-simulator",
        "slug": "digital-pet-simulator-game",
        "title": "Digital Pet Simulator",
        "category": "puzzle",
        "creator": "A23 Games",
        "path": "games/digital-pet-simulator/index.html",
        "thumbnail": "games/digital-pet-simulator/assets/icons/icon.jpg",
        "description": "Play Digital Pet Simulator online for free!",
        "longDescription": "Experience the thrill of Digital Pet Simulator. Complete challenges, achieve high scores, and enjoy this engaging puzzle game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "dragon_tower",
        "slug": "dragon_tower-game",
        "title": "Dragon Tower",
        "category": "action",
        "creator": "A23 Games",
        "path": "games/dragon_tower/index.html",
        "thumbnail": "games/dragon_tower/assets/icon.png",
        "description": "Play Dragon Tower online for free!",
        "longDescription": "Experience the thrill of Dragon Tower. Complete challenges, achieve high scores, and enjoy this engaging action game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "drift-racing-master",
        "slug": "drift-racing-master-game",
        "title": "Drift Racing Master",
        "category": "arcade",
        "creator": "A23 Games",
        "path": "games/drift-racing-master/index.html",
        "thumbnail": "games/drift-racing-master/assets/icon.png",
        "description": "Play Drift Racing Master online for free!",
        "longDescription": "Experience the thrill of Drift Racing Master. Complete challenges, achieve high scores, and enjoy this engaging arcade game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "dungeon-card-battle",
        "slug": "dungeon-card-battle-game",
        "title": "Dungeon Card Battle",
        "category": "arcade",
        "creator": "A23 Games",
        "path": "games/dungeon-card-battle/index.html",
        "thumbnail": "games/dungeon-card-battle/assets/icons/icon.svg",
        "description": "Play Dungeon Card Battle online for free!",
        "longDescription": "Experience the thrill of Dungeon Card Battle. Complete challenges, achieve high scores, and enjoy this engaging arcade game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "endless-runner",
        "slug": "endless-runner-game",
        "title": "Endless Runner",
        "category": "arcade",
        "creator": "A23 Games",
        "path": "games/endless-runner/index.html",
        "thumbnail": "games/endless-runner/assets/icons/icon.png",
        "description": "Play Endless Runner online for free!",
        "longDescription": "Experience the thrill of Endless Runner. Complete challenges, achieve high scores, and enjoy this engaging arcade game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "escape-room-master",
        "slug": "escape-room-master-game",
        "title": "Escape Room Master",
        "category": "sports",
        "creator": "A23 Games",
        "path": "games/escape-room-master/index.html",
        "thumbnail": "games/escape-room-master/assets/icons/icon.png",
        "description": "Play Escape Room Master online for free!",
        "longDescription": "Experience the thrill of Escape Room Master. Complete challenges, achieve high scores, and enjoy this engaging sports game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": true
    },
    {
        "id": "farming-simulation-lite",
        "slug": "farming-simulation-lite-game",
        "title": "Farming Simulation Lite",
        "category": "strategy",
        "creator": "A23 Games",
        "path": "games/farming-simulation-lite/index.html",
        "thumbnail": "games/farming-simulation-lite/assets/icons_ui.png",
        "description": "Play Farming Simulation Lite online for free!",
        "longDescription": "Experience the thrill of Farming Simulation Lite. Complete challenges, achieve high scores, and enjoy this engaging strategy game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "fashion-designer-studio",
        "slug": "fashion-designer-studio-game",
        "title": "Fashion Designer Studio",
        "category": "racing",
        "creator": "A23 Games",
        "path": "games/fashion-designer-studio/index.html",
        "thumbnail": "games/fashion-designer-studio/assets/images/icon.svg",
        "description": "Play Fashion Designer Studio online for free!",
        "longDescription": "Experience the thrill of Fashion Designer Studio. Complete challenges, achieve high scores, and enjoy this engaging racing game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "fast-car-racing",
        "slug": "fast-car-racing-game",
        "title": "Fast Car Racing",
        "category": "arcade",
        "creator": "A23 Games",
        "path": "games/Fast-Car-Racing/index.html",
        "thumbnail": "games/Fast-Car-Racing/icons/loading-logo.png",
        "description": "Play Fast Car Racing online for free!",
        "longDescription": "Experience the thrill of Fast Car Racing. Complete challenges, achieve high scores, and enjoy this engaging arcade game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "feed-the-frog",
        "slug": "feed-the-frog-game",
        "title": "Feed The Frog",
        "category": "puzzle",
        "creator": "A23 Games",
        "path": "games/feed-the-frog/index.html",
        "thumbnail": "games/feed-the-frog/icons/loading-logo.png",
        "description": "Play Feed The Frog online for free!",
        "longDescription": "Experience the thrill of Feed The Frog. Complete challenges, achieve high scores, and enjoy this engaging puzzle game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "firefighter-rescue-mission",
        "slug": "firefighter-rescue-mission-game",
        "title": "Firefighter Rescue Mission",
        "category": "sports",
        "creator": "A23 Games",
        "path": "games/firefighter-rescue-mission/index.html",
        "thumbnail": "games/firefighter-rescue-mission/assets/images/icon.png",
        "description": "Play Firefighter Rescue Mission online for free!",
        "longDescription": "Experience the thrill of Firefighter Rescue Mission. Complete challenges, achieve high scores, and enjoy this engaging sports game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "fishing-hook-timing",
        "slug": "fishing-hook-timing-game",
        "title": "Fishing Hook Timing",
        "category": "puzzle",
        "creator": "A23 Games",
        "path": "games/fishing-hook-timing/index.html",
        "thumbnail": "games/fishing-hook-timing/assets/thumb.png",
        "description": "Play Fishing Hook Timing online for free!",
        "longDescription": "Experience the thrill of Fishing Hook Timing. Complete challenges, achieve high scores, and enjoy this engaging puzzle game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "fishing-simulator-pro",
        "slug": "fishing-simulator-pro-game",
        "title": "Fishing Simulator Pro",
        "category": "puzzle",
        "creator": "A23 Games",
        "path": "games/fishing-simulator-pro/index.html",
        "thumbnail": "games/fishing-simulator-pro/assets/icons/app-icon.png",
        "description": "Play Fishing Simulator Pro online for free!",
        "longDescription": "Experience the thrill of Fishing Simulator Pro. Complete challenges, achieve high scores, and enjoy this engaging puzzle game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "flappy-bird",
        "slug": "flappy-bird-game",
        "title": "Flappy Bird",
        "category": "puzzle",
        "creator": "A23 Games",
        "path": "games/flappy-bird/index.html",
        "thumbnail": "games/flappy-bird/assets/thumbnail.png",
        "description": "Play Flappy Bird online for free!",
        "longDescription": "Experience the thrill of Flappy Bird. Complete challenges, achieve high scores, and enjoy this engaging puzzle game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "golf-precision-master",
        "slug": "golf-precision-master-game",
        "title": "Golf Precision Master",
        "category": "puzzle",
        "creator": "A23 Games",
        "path": "games/golf-precision-master/index.html",
        "thumbnail": "games/golf-precision-master/assets/icons/icon.png",
        "description": "Play Golf Precision Master online for free!",
        "longDescription": "Experience the thrill of Golf Precision Master. Complete challenges, achieve high scores, and enjoy this engaging puzzle game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "gravity-flip-platformer",
        "slug": "gravity-flip-platformer-game",
        "title": "Gravity Flip Platformer",
        "category": "strategy",
        "creator": "A23 Games",
        "path": "games/gravity-flip-platformer/index.html",
        "thumbnail": "games/gravity-flip-platformer/assets/icons/icon.png",
        "description": "Play Gravity Flip Platformer online for free!",
        "longDescription": "Experience the thrill of Gravity Flip Platformer. Complete challenges, achieve high scores, and enjoy this engaging strategy game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "gun_flip",
        "slug": "gun_flip-game",
        "title": "Gun Flip",
        "category": "strategy",
        "creator": "A23 Games",
        "path": "games/Gun_flip/index.html",
        "thumbnail": "games/Gun_flip/icons/loading-logo.png",
        "description": "Play Gun Flip online for free!",
        "longDescription": "Experience the thrill of Gun Flip. Complete challenges, achieve high scores, and enjoy this engaging strategy game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": true
    },
    {
        "id": "hacker-defense-tower",
        "slug": "hacker-defense-tower-game",
        "title": "Hacker Defense Tower",
        "category": "action",
        "creator": "A23 Games",
        "path": "games/hacker-defense-tower/index.html",
        "thumbnail": "games/hacker-defense-tower/assets/images/game_icon_1776864112240.png",
        "description": "Play Hacker Defense Tower online for free!",
        "longDescription": "Experience the thrill of Hacker Defense Tower. Complete challenges, achieve high scores, and enjoy this engaging action game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "hidden-easter-egg",
        "slug": "hidden-easter-egg-game",
        "title": "Hidden Easter Egg",
        "category": "sports",
        "creator": "A23 Games",
        "path": "games/hidden-easter-egg/index.html",
        "thumbnail": "games/hidden-easter-egg/icons/loading-logo.png",
        "description": "Play Hidden Easter Egg online for free!",
        "longDescription": "Experience the thrill of Hidden Easter Egg. Complete challenges, achieve high scores, and enjoy this engaging sports game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "idle-clicker-tycoon",
        "slug": "idle-clicker-tycoon-game",
        "title": "Idle Clicker Tycoon",
        "category": "action",
        "creator": "A23 Games",
        "path": "games/idle-clicker-tycoon/index.html",
        "thumbnail": "games/idle-clicker-tycoon/assets/icon.png",
        "description": "Play Idle Clicker Tycoon online for free!",
        "longDescription": "Experience the thrill of Idle Clicker Tycoon. Complete challenges, achieve high scores, and enjoy this engaging action game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "island-survival-builder",
        "slug": "island-survival-builder-game",
        "title": "Island Survival Builder",
        "category": "puzzle",
        "creator": "A23 Games",
        "path": "games/island-survival-builder/index.html",
        "thumbnail": "games/island-survival-builder/assets/images/icon.png",
        "description": "Play Island Survival Builder online for free!",
        "longDescription": "Experience the thrill of Island Survival Builder. Complete challenges, achieve high scores, and enjoy this engaging puzzle game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "jetpack-escape",
        "slug": "jetpack-escape-game",
        "title": "Jetpack Escape",
        "category": "arcade",
        "creator": "A23 Games",
        "path": "games/jetpack-escape/index.html",
        "thumbnail": "games/jetpack-escape/assets/thumb.png",
        "description": "Play Jetpack Escape online for free!",
        "longDescription": "Experience the thrill of Jetpack Escape. Complete challenges, achieve high scores, and enjoy this engaging arcade game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "knife-hit-master",
        "slug": "knife-hit-master-game",
        "title": "Knife Hit Master",
        "category": "strategy",
        "creator": "A23 Games",
        "path": "games/knife-hit-master/index.html",
        "thumbnail": "games/knife-hit-master/assets/thumb.png",
        "description": "Play Knife Hit Master online for free!",
        "longDescription": "Experience the thrill of Knife Hit Master. Complete challenges, achieve high scores, and enjoy this engaging strategy game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "laser-dodge-arena",
        "slug": "laser-dodge-arena-game",
        "title": "Laser Dodge Arena",
        "category": "action",
        "creator": "A23 Games",
        "path": "games/laser-dodge-arena/index.html",
        "thumbnail": "games/laser-dodge-arena/assets/thumb.png",
        "description": "Play Laser Dodge Arena online for free!",
        "longDescription": "Experience the thrill of Laser Dodge Arena. Complete challenges, achieve high scores, and enjoy this engaging action game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "match-3",
        "slug": "match-3-game",
        "title": "Match 3",
        "category": "puzzle",
        "creator": "A23 Games",
        "path": "games/match-3/index.html",
        "thumbnail": "games/match-3/assets/icons/icon.png",
        "description": "Play Match 3 online for free!",
        "longDescription": "Experience the thrill of Match 3. Complete challenges, achieve high scores, and enjoy this engaging puzzle game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "maze-escape-runner",
        "slug": "maze-escape-runner-game",
        "title": "Maze Escape Runner",
        "category": "strategy",
        "creator": "A23 Games",
        "path": "games/maze-escape-runner/index.html",
        "thumbnail": "games/maze-escape-runner/assets/images/icon.svg",
        "description": "Play Maze Escape Runner online for free!",
        "longDescription": "Experience the thrill of Maze Escape Runner. Complete challenges, achieve high scores, and enjoy this engaging strategy game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "memory-card-game",
        "slug": "memory-card-game-game",
        "title": "Memory Card Game",
        "category": "puzzle",
        "creator": "A23 Games",
        "path": "games/memory-card-game/index.html",
        "thumbnail": "games/memory-card-game/assets/icons/icon.png",
        "description": "Play Memory Card Game online for free!",
        "longDescription": "Experience the thrill of Memory Card Game. Complete challenges, achieve high scores, and enjoy this engaging puzzle game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "merge-battle-evolution",
        "slug": "merge-battle-evolution-game",
        "title": "Merge Battle Evolution",
        "category": "puzzle",
        "creator": "A23 Games",
        "path": "games/merge-battle-evolution/index.html",
        "thumbnail": "games/merge-battle-evolution/assets/icons/game_icon.svg",
        "description": "Play Merge Battle Evolution online for free!",
        "longDescription": "Experience the thrill of Merge Battle Evolution. Complete challenges, achieve high scores, and enjoy this engaging puzzle game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": true
    },
    {
        "id": "mimstris",
        "slug": "mimstris-game",
        "title": "Mimstris",
        "category": "strategy",
        "creator": "A23 Games",
        "path": "games/mimstris/index.html",
        "thumbnail": "assets/thumbs/mimstris.png",
        "description": "Play Mimstris online for free!",
        "longDescription": "Experience the thrill of Mimstris. Complete challenges, achieve high scores, and enjoy this engaging strategy game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "mini-golf-challenge",
        "slug": "mini-golf-challenge-game",
        "title": "Mini Golf Challenge",
        "category": "strategy",
        "creator": "A23 Games",
        "path": "games/mini-golf-challenge/index.html",
        "thumbnail": "games/mini-golf-challenge/assets/thumb.png",
        "description": "Play Mini Golf Challenge online for free!",
        "longDescription": "Experience the thrill of Mini Golf Challenge. Complete challenges, achieve high scores, and enjoy this engaging strategy game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "mini_golf",
        "slug": "mini_golf-game",
        "title": "Mini Golf",
        "category": "action",
        "creator": "A23 Games",
        "path": "games/mini_golf/index.html",
        "thumbnail": "games/mini_golf/icons/loading-logo.png",
        "description": "Play Mini Golf online for free!",
        "longDescription": "Experience the thrill of Mini Golf. Complete challenges, achieve high scores, and enjoy this engaging action game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "monster-defense-clash",
        "slug": "monster-defense-clash-game",
        "title": "Monster Defense Clash",
        "category": "sports",
        "creator": "A23 Games",
        "path": "games/monster-defense-clash/index.html",
        "thumbnail": "games/monster-defense-clash/assets/icons/icon.svg",
        "description": "Play Monster Defense Clash online for free!",
        "longDescription": "Experience the thrill of Monster Defense Clash. Complete challenges, achieve high scores, and enjoy this engaging sports game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "music-dj-simulator",
        "slug": "music-dj-simulator-game",
        "title": "Music Dj Simulator",
        "category": "action",
        "creator": "A23 Games",
        "path": "games/music-dj-simulator/index.html",
        "thumbnail": "games/music-dj-simulator/assets/images/icon.png",
        "description": "Play Music Dj Simulator online for free!",
        "longDescription": "Experience the thrill of Music Dj Simulator. Complete challenges, achieve high scores, and enjoy this engaging action game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "neon-breakout",
        "slug": "neon-breakout-game",
        "title": "Neon Breakout",
        "category": "sports",
        "creator": "A23 Games",
        "path": "games/neon-breakout/index.html",
        "thumbnail": "games/neon-breakout/assets/thumb.png",
        "description": "Play Neon Breakout online for free!",
        "longDescription": "Experience the thrill of Neon Breakout. Complete challenges, achieve high scores, and enjoy this engaging sports game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "neon-racer-arcade",
        "slug": "neon-racer-arcade-game",
        "title": "Neon Racer Arcade",
        "category": "racing",
        "creator": "A23 Games",
        "path": "games/neon-racer-arcade/index.html",
        "thumbnail": "assets/thumbs/neon-racer-arcade.png",
        "description": "Play Neon Racer Arcade online for free!",
        "longDescription": "Experience the thrill of Neon Racer Arcade. Complete challenges, achieve high scores, and enjoy this engaging racing game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "pirate-ship-battle",
        "slug": "pirate-ship-battle-game",
        "title": "Pirate Ship Battle",
        "category": "action",
        "creator": "A23 Games",
        "path": "games/pirate-ship-battle/index.html",
        "thumbnail": "games/pirate-ship-battle/assets/icons/icon.svg",
        "description": "Play Pirate Ship Battle online for free!",
        "longDescription": "Experience the thrill of Pirate Ship Battle. Complete challenges, achieve high scores, and enjoy this engaging action game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "planet-defense-orbit",
        "slug": "planet-defense-orbit-game",
        "title": "Planet Defense Orbit",
        "category": "strategy",
        "creator": "A23 Games",
        "path": "games/planet-defense-orbit/index.html",
        "thumbnail": "games/planet-defense-orbit/assets/images/icon.png",
        "description": "Play Planet Defense Orbit online for free!",
        "longDescription": "Experience the thrill of Planet Defense Orbit. Complete challenges, achieve high scores, and enjoy this engaging strategy game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "police-chase-escape",
        "slug": "police-chase-escape-game",
        "title": "Police Chase Escape",
        "category": "puzzle",
        "creator": "A23 Games",
        "path": "games/police-chase-escape/index.html",
        "thumbnail": "games/police-chase-escape/assets/images/icon.png",
        "description": "Play Police Chase Escape online for free!",
        "longDescription": "Experience the thrill of Police Chase Escape. Complete challenges, achieve high scores, and enjoy this engaging puzzle game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "pop-balloons",
        "slug": "pop-balloons-game",
        "title": "Pop Balloons",
        "category": "arcade",
        "creator": "A23 Games",
        "path": "games/pop-balloons/index.html",
        "thumbnail": "games/pop-balloons/icons/loading-logo.png",
        "description": "Play Pop Balloons online for free!",
        "longDescription": "Experience the thrill of Pop Balloons. Complete challenges, achieve high scores, and enjoy this engaging arcade game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": true
    },
    {
        "id": "pop_the_balloons",
        "slug": "pop_the_balloons-game",
        "title": "Pop The Balloons",
        "category": "arcade",
        "creator": "A23 Games",
        "path": "games/pop_the_balloons/index.html",
        "thumbnail": "games/pop_the_balloons/icons/loading-logo.png",
        "description": "Play Pop The Balloons online for free!",
        "longDescription": "Experience the thrill of Pop The Balloons. Complete challenges, achieve high scores, and enjoy this engaging arcade game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "quantum-cube-solver",
        "slug": "quantum-cube-solver-game",
        "title": "Quantum Cube Solver",
        "category": "puzzle",
        "creator": "A23 Games",
        "path": "games/quantum-cube-solver/index.html",
        "thumbnail": "games/quantum-cube-solver/icon.png",
        "description": "Play Quantum Cube Solver online for free!",
        "longDescription": "Experience the thrill of Quantum Cube Solver. Complete challenges, achieve high scores, and enjoy this engaging puzzle game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "restaurant-rush-manager",
        "slug": "restaurant-rush-manager-game",
        "title": "Restaurant Rush Manager",
        "category": "puzzle",
        "creator": "A23 Games",
        "path": "games/restaurant-rush-manager/index.html",
        "thumbnail": "games/restaurant-rush-manager/assets/icon.png",
        "description": "Play Restaurant Rush Manager online for free!",
        "longDescription": "Experience the thrill of Restaurant Rush Manager. Complete challenges, achieve high scores, and enjoy this engaging puzzle game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "rhythm-beat-runner",
        "slug": "rhythm-beat-runner-game",
        "title": "Rhythm Beat Runner",
        "category": "strategy",
        "creator": "A23 Games",
        "path": "games/rhythm-beat-runner/index.html",
        "thumbnail": "assets/thumbs/rhythm-beat-runner.png",
        "description": "Play Rhythm Beat Runner online for free!",
        "longDescription": "Experience the thrill of Rhythm Beat Runner. Complete challenges, achieve high scores, and enjoy this engaging strategy game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "robot-factory-automation",
        "slug": "robot-factory-automation-game",
        "title": "Robot Factory Automation",
        "category": "sports",
        "creator": "A23 Games",
        "path": "games/robot-factory-automation/index.html",
        "thumbnail": "games/robot-factory-automation/assets/images/icon.png",
        "description": "Play Robot Factory Automation online for free!",
        "longDescription": "Experience the thrill of Robot Factory Automation. Complete challenges, achieve high scores, and enjoy this engaging sports game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "robot-jump-escape",
        "slug": "robot-jump-escape-game",
        "title": "Robot Jump Escape",
        "category": "strategy",
        "creator": "A23 Games",
        "path": "games/robot-jump-escape/index.html",
        "thumbnail": "games/robot-jump-escape/assets/thumb.png",
        "description": "Play Robot Jump Escape online for free!",
        "longDescription": "Experience the thrill of Robot Jump Escape. Complete challenges, achieve high scores, and enjoy this engaging strategy game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "rolling-ball-maze-3d",
        "slug": "rolling-ball-maze-3d-game",
        "title": "Rolling Ball Maze 3d",
        "category": "action",
        "creator": "A23 Games",
        "path": "games/rolling-ball-maze-3d/index.html",
        "thumbnail": "games/rolling-ball-maze-3d/assets/thumb.png",
        "description": "Play Rolling Ball Maze 3d online for free!",
        "longDescription": "Experience the thrill of Rolling Ball Maze 3d. Complete challenges, achieve high scores, and enjoy this engaging action game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "rope-hero-swing",
        "slug": "rope-hero-swing-game",
        "title": "Rope Hero Swing",
        "category": "racing",
        "creator": "A23 Games",
        "path": "games/rope-hero-swing/index.html",
        "thumbnail": "games/rope-hero-swing/assets/icons/icon.png",
        "description": "Play Rope Hero Swing online for free!",
        "longDescription": "Experience the thrill of Rope Hero Swing. Complete challenges, achieve high scores, and enjoy this engaging racing game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "samegame",
        "slug": "samegame-game",
        "title": "Samegame",
        "category": "racing",
        "creator": "A23 Games",
        "path": "games/samegame/index.html",
        "thumbnail": "assets/thumbs/samegame.png",
        "description": "Play Samegame online for free!",
        "longDescription": "Experience the thrill of Samegame. Complete challenges, achieve high scores, and enjoy this engaging racing game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "shadow-ninja-3d",
        "slug": "shadow-ninja-3d-game",
        "title": "Shadow Ninja 3d",
        "category": "strategy",
        "creator": "A23 Games",
        "path": "games/shadow-ninja-3d/index.html",
        "thumbnail": "games/shadow-ninja-3d/icon.png",
        "description": "Play Shadow Ninja 3d online for free!",
        "longDescription": "Experience the thrill of Shadow Ninja 3d. Complete challenges, achieve high scores, and enjoy this engaging strategy game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "shadow-ninja-fight",
        "slug": "shadow-ninja-fight-game",
        "title": "Shadow Ninja Fight",
        "category": "arcade",
        "creator": "A23 Games",
        "path": "games/shadow-ninja-fight/index.html",
        "thumbnail": "games/shadow-ninja-fight/assets/icons/icon.png",
        "description": "Play Shadow Ninja Fight online for free!",
        "longDescription": "Experience the thrill of Shadow Ninja Fight. Complete challenges, achieve high scores, and enjoy this engaging arcade game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": true
    },
    {
        "id": "shadow-runner-escape",
        "slug": "shadow-runner-escape-game",
        "title": "Shadow Runner Escape",
        "category": "racing",
        "creator": "A23 Games",
        "path": "games/shadow-runner-escape/index.html",
        "thumbnail": "games/shadow-runner-escape/assets/thumb.png",
        "description": "Play Shadow Runner Escape online for free!",
        "longDescription": "Experience the thrill of Shadow Runner Escape. Complete challenges, achieve high scores, and enjoy this engaging racing game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "sliding-puzzle",
        "slug": "sliding-puzzle-game",
        "title": "Sliding Puzzle",
        "category": "puzzle",
        "creator": "A23 Games",
        "path": "games/sliding-puzzle/index.html",
        "thumbnail": "games/sliding-puzzle/assets/icons/game-icon.png",
        "description": "Play Sliding Puzzle online for free!",
        "longDescription": "Experience the thrill of Sliding Puzzle. Complete challenges, achieve high scores, and enjoy this engaging puzzle game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "smart-home-puzzle",
        "slug": "smart-home-puzzle-game",
        "title": "Smart Home Puzzle",
        "category": "arcade",
        "creator": "A23 Games",
        "path": "games/smart-home-puzzle/index.html",
        "thumbnail": "games/smart-home-puzzle/assets/icon.png",
        "description": "Play Smart Home Puzzle online for free!",
        "longDescription": "Experience the thrill of Smart Home Puzzle. Complete challenges, achieve high scores, and enjoy this engaging arcade game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "snake-2026",
        "slug": "snake-2026-game",
        "title": "Snake 2026",
        "category": "action",
        "creator": "A23 Games",
        "path": "games/snake-2026/index.html",
        "thumbnail": "games/snake-2026/icons/loading-logo.png",
        "description": "Play Snake 2026 online for free!",
        "longDescription": "Experience the thrill of Snake 2026. Complete challenges, achieve high scores, and enjoy this engaging action game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "space-colony-manager",
        "slug": "space-colony-manager-game",
        "title": "Space Colony Manager",
        "category": "sports",
        "creator": "A23 Games",
        "path": "games/space-colony-manager/index.html",
        "thumbnail": "games/space-colony-manager/assets/icons/icon.png",
        "description": "Play Space Colony Manager online for free!",
        "longDescription": "Experience the thrill of Space Colony Manager. Complete challenges, achieve high scores, and enjoy this engaging sports game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "space-dodge-mission",
        "slug": "space-dodge-mission-game",
        "title": "Space Dodge Mission",
        "category": "puzzle",
        "creator": "A23 Games",
        "path": "games/space-dodge-mission/index.html",
        "thumbnail": "games/space-dodge-mission/assets/thumb.png",
        "description": "Play Space Dodge Mission online for free!",
        "longDescription": "Experience the thrill of Space Dodge Mission. Complete challenges, achieve high scores, and enjoy this engaging puzzle game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "space-shooter",
        "slug": "space-shooter-game",
        "title": "Space Shooter",
        "category": "sports",
        "creator": "A23 Games",
        "path": "games/space-shooter/index.html",
        "thumbnail": "games/space-shooter/assets/images/icon.png",
        "description": "Play Space Shooter online for free!",
        "longDescription": "Experience the thrill of Space Shooter. Complete challenges, achieve high scores, and enjoy this engaging sports game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "spy-gadget-mission",
        "slug": "spy-gadget-mission-game",
        "title": "Spy Gadget Mission",
        "category": "puzzle",
        "creator": "A23 Games",
        "path": "games/spy-gadget-mission/index.html",
        "thumbnail": "games/spy-gadget-mission/assets/images/icon.png",
        "description": "Play Spy Gadget Mission online for free!",
        "longDescription": "Experience the thrill of Spy Gadget Mission. Complete challenges, achieve high scores, and enjoy this engaging puzzle game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "stack-jump-tower",
        "slug": "stack-jump-tower-game",
        "title": "Stack Jump Tower",
        "category": "arcade",
        "creator": "A23 Games",
        "path": "games/stack-jump-tower/index.html",
        "thumbnail": "games/stack-jump-tower/assets/thumb.png",
        "description": "Play Stack Jump Tower online for free!",
        "longDescription": "Experience the thrill of Stack Jump Tower. Complete challenges, achieve high scores, and enjoy this engaging arcade game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "stack-tower-builder",
        "slug": "stack-tower-builder-game",
        "title": "Stack Tower Builder",
        "category": "action",
        "creator": "A23 Games",
        "path": "games/stack-tower-builder/index.html",
        "thumbnail": "games/stack-tower-builder/assets/icons/icon.png",
        "description": "Play Stack Tower Builder online for free!",
        "longDescription": "Experience the thrill of Stack Tower Builder. Complete challenges, achieve high scores, and enjoy this engaging action game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "sudoku-ultimate",
        "slug": "sudoku-ultimate-game",
        "title": "Sudoku Ultimate",
        "category": "racing",
        "creator": "A23 Games",
        "path": "games/sudoku-ultimate/index.html",
        "thumbnail": "games/sudoku-ultimate/assets/icons/icon.png",
        "description": "Play Sudoku Ultimate online for free!",
        "longDescription": "Experience the thrill of Sudoku Ultimate. Complete challenges, achieve high scores, and enjoy this engaging racing game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": true
    },
    {
        "id": "survival-shooter-arena",
        "slug": "survival-shooter-arena-game",
        "title": "Survival Shooter Arena",
        "category": "strategy",
        "creator": "A23 Games",
        "path": "games/survival-shooter-arena/index.html",
        "thumbnail": "games/survival-shooter-arena/assets/bg.png",
        "description": "Play Survival Shooter Arena online for free!",
        "longDescription": "Experience the thrill of Survival Shooter Arena. Complete challenges, achieve high scores, and enjoy this engaging strategy game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "tank-battle-war",
        "slug": "tank-battle-war-game",
        "title": "Tank Battle War",
        "category": "arcade",
        "creator": "A23 Games",
        "path": "games/tank-battle-war/index.html",
        "thumbnail": "games/tank-battle-war/assets/icons/icon.svg",
        "description": "Play Tank Battle War online for free!",
        "longDescription": "Experience the thrill of Tank Battle War. Complete challenges, achieve high scores, and enjoy this engaging arcade game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "tank-shooter-arena",
        "slug": "tank-shooter-arena-game",
        "title": "Tank Shooter Arena",
        "category": "puzzle",
        "creator": "A23 Games",
        "path": "games/tank-shooter-arena/index.html",
        "thumbnail": "games/tank-shooter-arena/assets/thumb.png",
        "description": "Play Tank Shooter Arena online for free!",
        "longDescription": "Experience the thrill of Tank Shooter Arena. Complete challenges, achieve high scores, and enjoy this engaging puzzle game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "tap-tap-jump",
        "slug": "tap-tap-jump-game",
        "title": "Tap Tap Jump",
        "category": "puzzle",
        "creator": "A23 Games",
        "path": "games/tap-tap-jump/index.html",
        "thumbnail": "games/tap-tap-jump/assets/icons/icon.png",
        "description": "Play Tap Tap Jump online for free!",
        "longDescription": "Experience the thrill of Tap Tap Jump. Complete challenges, achieve high scores, and enjoy this engaging puzzle game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "teeter",
        "slug": "teeter-game",
        "title": "Teeter",
        "category": "action",
        "creator": "A23 Games",
        "path": "games/teeter/index.html",
        "thumbnail": "assets/thumbs/teeter.png",
        "description": "Play Teeter online for free!",
        "longDescription": "Experience the thrill of Teeter. Complete challenges, achieve high scores, and enjoy this engaging action game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "tic-tac-toe-game",
        "slug": "tic-tac-toe-game-game",
        "title": "Tic Tac Toe Game",
        "category": "action",
        "creator": "A23 Games",
        "path": "games/tic-tac-toe-game/index.html",
        "thumbnail": "games/tic-tac-toe-game/assets/icons/game-icon.png",
        "description": "Play Tic Tac Toe Game online for free!",
        "longDescription": "Experience the thrill of Tic Tac Toe Game. Complete challenges, achieve high scores, and enjoy this engaging action game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "time-travel-puzzle",
        "slug": "time-travel-puzzle-game",
        "title": "Time Travel Puzzle",
        "category": "strategy",
        "creator": "A23 Games",
        "path": "games/time-travel-puzzle/index.html",
        "thumbnail": "games/time-travel-puzzle/assets/icons/icon.svg",
        "description": "Play Time Travel Puzzle online for free!",
        "longDescription": "Experience the thrill of Time Travel Puzzle. Complete challenges, achieve high scores, and enjoy this engaging strategy game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "tower_defense",
        "slug": "tower_defense-game",
        "title": "Tower Defense",
        "category": "sports",
        "creator": "A23 Games",
        "path": "games/tower_defense/index.html",
        "thumbnail": "games/tower_defense/icon.svg",
        "description": "Play Tower Defense online for free!",
        "longDescription": "Experience the thrill of Tower Defense. Complete challenges, achieve high scores, and enjoy this engaging sports game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "tower_game",
        "slug": "tower_game-game",
        "title": "Tower Game",
        "category": "arcade",
        "creator": "A23 Games",
        "path": "games/tower_game/index.html",
        "thumbnail": "assets/thumbs/tower_game.png",
        "description": "Play Tower Game online for free!",
        "longDescription": "Experience the thrill of Tower Game. Complete challenges, achieve high scores, and enjoy this engaging arcade game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "traffic-rush-control",
        "slug": "traffic-rush-control-game",
        "title": "Traffic Rush Control",
        "category": "racing",
        "creator": "A23 Games",
        "path": "games/traffic-rush-control/index.html",
        "thumbnail": "games/traffic-rush-control/assets/icons/icon.png",
        "description": "Play Traffic Rush Control online for free!",
        "longDescription": "Experience the thrill of Traffic Rush Control. Complete challenges, achieve high scores, and enjoy this engaging racing game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "train-control-manager",
        "slug": "train-control-manager-game",
        "title": "Train Control Manager",
        "category": "arcade",
        "creator": "A23 Games",
        "path": "games/train-control-manager/index.html",
        "thumbnail": "games/train-control-manager/assets/icons/thumbnail.svg",
        "description": "Play Train Control Manager online for free!",
        "longDescription": "Experience the thrill of Train Control Manager. Complete challenges, achieve high scores, and enjoy this engaging arcade game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": true
    },
    {
        "id": "underwater-explorer",
        "slug": "underwater-explorer-game",
        "title": "Underwater Explorer",
        "category": "strategy",
        "creator": "A23 Games",
        "path": "games/underwater-explorer/index.html",
        "thumbnail": "games/underwater-explorer/assets/icons/icon.png",
        "description": "Play Underwater Explorer online for free!",
        "longDescription": "Experience the thrill of Underwater Explorer. Complete challenges, achieve high scores, and enjoy this engaging strategy game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "void_breaker",
        "slug": "void_breaker-game",
        "title": "Void Breaker",
        "category": "arcade",
        "creator": "A23 Games",
        "path": "games/void_breaker/index.html",
        "thumbnail": "games/void_breaker/assets/icon.png",
        "description": "Play Void Breaker online for free!",
        "longDescription": "Experience the thrill of Void Breaker. Complete challenges, achieve high scores, and enjoy this engaging arcade game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "watermelon",
        "slug": "watermelon-game",
        "title": "Watermelon",
        "category": "strategy",
        "creator": "A23 Games",
        "path": "games/watermelon/index.html",
        "thumbnail": "assets/thumbs/watermelon.png",
        "description": "Play Watermelon online for free!",
        "longDescription": "Experience the thrill of Watermelon. Complete challenges, achieve high scores, and enjoy this engaging strategy game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "word-connect-master",
        "slug": "word-connect-master-game",
        "title": "Word Connect Master",
        "category": "racing",
        "creator": "A23 Games",
        "path": "games/word-connect-master/index.html",
        "thumbnail": "games/word-connect-master/assets/icons/thumbnail.png",
        "description": "Play Word Connect Master online for free!",
        "longDescription": "Experience the thrill of Word Connect Master. Complete challenges, achieve high scores, and enjoy this engaging racing game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    },
    {
        "id": "zombie-shooter-mini",
        "slug": "zombie-shooter-mini-game",
        "title": "Zombie Shooter Mini",
        "category": "action",
        "creator": "A23 Games",
        "path": "games/zombie-shooter-mini/index.html",
        "thumbnail": "games/zombie-shooter-mini/assets/thumb.png",
        "description": "Play Zombie Shooter Mini online for free!",
        "longDescription": "Experience the thrill of Zombie Shooter Mini. Complete challenges, achieve high scores, and enjoy this engaging action game.",
        "howToPlay": "Follow the on-screen instructions to play. Use your mouse or touch controls to interact.",
        "isTrending": false
    }
];